#!/bin/bash

# Copyright 2013 Wenjun Deng <wdeng@wdeng.info>

# This file is part of Omega Tools.

# Omega Tools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Omega Tools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Omega Tools.  If not, see <http://www.gnu.org/licenses/>.

VERSION='2013-03-11 12:11:03-04:00'

if [ -z "${1}" ]
then
	echo
	echo "mpost_mps version ${VERSION}"
	echo
	echo "A wrapper that does these 4 things in sequence:"
	echo "1. change to the directory of the mpost script file;"
	echo "2. call mpost on the script file;"
	echo "3. rename generated .0 file into .mps file;"
	echo "4. rename generated .log file into _mp.log file."
	echo
	echo "Usage: mpost_mps <mpost script file>"
	echo
	exit
fi
if [ ! -f $1 ]
then
	echo "File $1 does not exist."
	exit 1
fi

dir=`dirname $1`
file=`basename $1`

cd $dir
mpost $file
mv ${file%.*}.0 ${file%.*}.mps
mv ${file%.*}.log ${file%.*}_mp.log

