#!/bin/bash

# Copyright 2012 Wenjun Deng <wdeng@wdeng.info>

# This file is part of Omega Tools.

# Omega Tools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Omega Tools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Omega Tools.  If not, see <http://www.gnu.org/licenses/>.

VERSION='2012-04-16 00:25:25-04:00'

if [ -z "${1}" ];
then
	echo
	echo "updateversion_sh version ${VERSION}"
	echo
	echo "Updates the VERSION string to current time in (ba)sh script."
	echo
	echo "Usage: updateversion_sh <(ba)sh script file name>"
	echo
	exit
fi
if [ ! -f ${1} ];
then
	echo "File ${1} does not exist."
	exit 1
fi

# get current time as version string
v=`date --rfc-3339=seconds`

sed "s/^VERSION=.*\$/VERSION='${v}'/" < ${1} > ${1}~
mv -f ${1}~ ${1}

