#!/bin/bash

# Copyright 2012 Wenjun Deng <wdeng@wdeng.info>

# This file is part of Omega Tools.

# Omega Tools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Omega Tools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Omega Tools.  If not, see <http://www.gnu.org/licenses/>.

# This is a git pre-commit script to replace version strings by current time.

VERSION='2012-04-15 23:53:44-04:00'
FILES='hooks/pre-commit makedependlatex makedependgp gpmp2latexmp gpmpextendpalette gpmpuseexpal'

# get current time as version string
v=`date --rfc-3339=seconds`

# go to the repository root
cd `git rev-parse --show-toplevel`

# check working tree files, if modified, replace version string
mf=''
for f in $FILES
do
	git status --porcelain ${f} | grep "^[AM][ MD]"
	if [ $? -eq 0 ]
	then
		mf="${mf} ${f}"
		if [ -s ${f} ]
		then
			sed "s/^VERSION=.*\$/VERSION='${v}'/" < ${f} > ${f}~
			mv ${f}~ ${f}
		fi
	fi
done

# put working tree aside, get indexed files
git stash --keep-index

# replace version strings in indexed files
for f in $mf
do
	sed "s/^VERSION=.*\$/VERSION='${v}'/" < ${f} > ${f}~
	mv ${f}~ ${f}
done

# index the new version string
git add $mf

# put back working tree
git stash pop

